// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrations should run against neons DIRECT connection, not the pooler.
    // runtime keeps using the pooled DATABASE_URL from utils/config.ts
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});